# Generated by Django 5.1.7 on 2025-09-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_uploadimagetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimagetest',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
