# Generated by Django 5.1.7 on 2025-10-22 05:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_blocklist_messages_profile_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
