# Generated by Django 5.1.7 on 2025-10-22 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_blocklist_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocklist',
            name='created_at',
        ),
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
