# Generated by Django 5.1.7 on 2025-10-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_remove_blocklist_created_at_messages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='viewed',
            field=models.BooleanField(default=0),
        ),
    ]
