# Generated by Django 5.1.7 on 2025-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0012_messages_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desc',
            field=models.TextField(default='No desc.', max_length=222),
        ),
    ]
