# Generated by Django 5.1.7 on 2025-12-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0014_alter_messages_user2_alter_blocklist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blocklist',
            unique_together=set(),
        ),
    ]
