# Generated by Django 5.1.7 on 2025-12-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0017_remove_task_category_remove_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='viewed',
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
