# Generated by Django 5.1.7 on 2025-12-21 05:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0018_remove_messages_viewed_alter_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='blocklist',
            index=models.Index(fields=['user1', 'user2'], name='blocklistindex'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['user1', 'user2'], name='messagesindex'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['id'], name='taskindex'),
        ),
    ]
